apiVersion: v1
kind: Service
metadata:
  name: ai-assistant-rag
  namespace: ai-assistant-rag
  labels:
    app: ai-assistant-rag
spec:
  type: LoadBalancer
  ports:
  - port: 8503
    targetPort: 8503
    protocol: TCP
    name: http
  selector:
    app: ai-assistant-rag
